<?php 
    //Register custom strings support by theme
    pll_register_string( 'personal_information', 'Personal Information', 'modern-website', false);
    pll_register_string( 'required_fields', 'Required fields', 'modern-website', false);
    pll_register_string( 'fieldrequired', 'Field is required.', 'modern-website', false );
    pll_register_string( 'looksgood', 'Looks good!', 'modern-website', false );
    pll_register_string( 'namelabel', 'Name', 'modern-website', false );
    pll_register_string( 'name_placeholder', 'Name Placeholder', 'modern-website', false );
    pll_register_string( 'fullname_placeholder', 'Full Name (First, Surname)', 'modern-website', false );
    pll_register_string( 'email_address_label', 'E-mail Address', 'modern-website', false );
    pll_register_string( 'email_placeholder', 'Preferred email to contact you', 'modern-website', false );
    pll_register_string( 'address_label', 'Address', 'modern-website', false);
    pll_register_string( 'address_placeholder', 'Number of street and street name here', 'modern-website', false);
    pll_register_string( 'address_placeholder_second', 'Address Placeholder', 'modern-website', false);
    pll_register_string( 'city_label', 'City', 'modern-website', false);
    pll_register_string( 'city_placeholder', 'City Placeholder', 'modern-website', true);
    pll_register_string( 'check_term_codition', 'I have read and understood the terms and conditions', 'modern-website', false);
    pll_register_string( 'province_label', 'Province', 'modern-website', false);
    pll_register_string( 'use_all_provinces', 'Use Dropdown for all provinces in  Canada', 'modern-website', true);
    pll_register_string( 'postal_code_label', 'Postal Code', 'modern-website', false);
    pll_register_string( 'postal_code_placeholder', 'e.g l4ylE4', 'modern-website', false);
    pll_register_string( 'home_phone_label', 'Home Phone', 'modern-website', false);
    pll_register_string( 'home_phone_placeholder', 'Home Phone Placeholder', 'modern-website', false);
    pll_register_string( 'cell_phone_label', 'Cell Phone (if applicable)', 'modern-website', false);
    pll_register_string( 'cell_phone_label_rfc_form', 'Cell Phone', 'modern-website', false);
    pll_register_string( 'home_address_label_rfc_form', 'Home Address', 'modern-website', false);
    pll_register_string( 'date_of_birth_label_rfc_form', 'Date of birth', 'modern-website', false);
    pll_register_string( 'location_of_interest_label_rfc_form', 'Location of Interest', 'modern-website', false);
    pll_register_string( 'preferred_area_label_rfc_form', 'Preferred Area', 'modern-website', false);
    pll_register_string( 'how_did_you_hear_about_our_franchising_opportunity_label_rfc_form', 'How did you hear about our franchising opportunity?', 'modern-website', false);
    pll_register_string( 'please_select_one_label_rfc_form', 'Please Select One', 'modern-website', false);
    pll_register_string( 'word_of_mouth_label_rfc_form', 'Word of mouth', 'modern-website', false);
    pll_register_string( 'regular_customer_label_rfc_form', 'I am/was a regular customer', 'modern-website', false);
    pll_register_string( 'worked_working_as_mf_label_rfc_form', 'I have worked/am working as a Modern franchisee', 'modern-website', false);
    pll_register_string( 'referral_garden_label_rfc_form', 'Referral', 'modern-website', false);
    pll_register_string( 'online_advertisement_label_rfc_form', 'Online advertisement', 'modern-website', false);
    pll_register_string( 'immediately_label_rfc_form', 'Immediately', 'modern-website', false);
    pll_register_string( 'within_months_short_label_rfc_form', 'Within 3-6 months', 'modern-website', false);
    pll_register_string( 'within_months_longer_label_rfc_form', 'Within 7-12 months', 'modern-website', false);
    pll_register_string( 'year_or_more_label_rfc_form', '1 year or more', 'modern-website', false);
    pll_register_string( 'owner_operator_label_rfc_form', 'Owner-operator', 'modern-website', false);
    pll_register_string( 'absentee_owner_label_rfc_form', 'Absentee owner', 'modern-website', false);
    pll_register_string( 'current_business_owner_label_rfc_form', 'Yes, I am currently a business owner', 'modern-website', false);
    pll_register_string( 'owned_business_owner_past_label_rfc_form', 'Yes, I owned business in the past', 'modern-website', false);
    pll_register_string( 'provide_details_label_rfc_form', 'If yes, please be specific and provide details', 'modern-website', false);
    pll_register_string( 'please_explain_label_rfc_form', 'If no, please explain', 'modern-website', false);
    pll_register_string( 'please_provide_more_info_label_rfc_form', 'Yes, provide more information:', 'modern-website', false);
    pll_register_string( 'yes_explain_label_rfc_form', 'Yes, explain:', 'modern-website', false);
    pll_register_string( 'looking_to_start_label_rfc_form', 'Looking to start', 'modern-website', false);
    pll_register_string( 'previous_franchise_experience_label_rfc_form', 'Previous Franchise Experience', 'modern-website', false);
    pll_register_string( 'anticipated_owners_involvement_label_rfc_form', 'Anticipated owner’s involvement', 'modern-website', false);
    pll_register_string( 'are_you_currently_employed_label_rfc_form', 'Are you currently employed?', 'modern-website', false);
    pll_register_string( 'what_is_your_current_occupation_label_rfc_form', 'What is your current occupation?', 'modern-website', false);
    pll_register_string( 'recent_job_label_rfc_form', 'What is/was your single most favorite attribute of your current/most recent job?', 'modern-website', false);
    pll_register_string( 'current_resume_optional_label_rfc_form', 'Upload your current resume (optional)', 'modern-website', false);
    pll_register_string( 'owned_business_label_rfc_form', 'Have you ever owned a business?', 'modern-website', false);
    pll_register_string( 'business_partners_label_rfc_form', 'Will you have business partners?', 'modern-website', false);
    pll_register_string( 'relative_in_business_label_rfc_form', 'Will your spouse/relative be a partner or employee in the business?', 'modern-website', false);
    pll_register_string( 'relative_in_business_details_label_rfc_form', 'Details', 'modern-website', false);
    pll_register_string( 'sole_income_source_label_rfc_form', 'Would this business be your sole income source?', 'modern-website', false);
    pll_register_string( 'sole_income_source_explain_label_rfc_form', 'Explain', 'modern-website', false);
    pll_register_string( 'new_franchise_business_reason_label_rfc_form', 'Why do you want to be a franchisee instead of starting a non-franchised business?', 'modern-website', false);
    pll_register_string( 'skills_experience_franchisee_label_rfc_form', 'What skills/experience do you have that will help you be successful in this business?', 'modern-website', false);
    pll_register_string( 'personal_goals_label_rfc_form', 'Why do you think this franchise will enable you to reach your personal goals?', 'modern-website', false);
    pll_register_string( 'lawsuit_label_rfc_form', 'Are you now, or have you ever been party to any lawsuit - either as defendant or plaintiff?', 'modern-website', false);
    pll_register_string( 'lawsuit_more_info_label_rfc_form', 'Provide more information', 'modern-website', false);
    pll_register_string( 'convicted_label_rfc_form', 'Have you ever been convicted of a felony?', 'modern-website', false);
    pll_register_string( 'bankruptcy_label_rfc_form', 'Have you ever filed for bankruptcy?', 'modern-website', false);
    pll_register_string( 'bankruptcy_date_filed_label_rfc_form', 'Date filed', 'modern-website', false);
    pll_register_string( 'bankruptcy_date_discharged_label_rfc_form', 'Date discharged', 'modern-website', false);
    pll_register_string( 'capital_available_label_rfc_form', 'Capital Available to Invest', 'modern-website', false);
    pll_register_string( 'capital_cash_label_rfc_form', 'Cash', 'modern-website', false);
    pll_register_string( 'capital_stocks_label_rfc_form', 'Stocks/Bonds/mutual funds', 'modern-website', false);
    pll_register_string( 'capital_rrsp_label_rfc_form', 'RRSP/TFSA/pension funds', 'modern-website', false);
    pll_register_string( 'capital_market_value_label_rfc_form', 'Market value of real estate you own', 'modern-website', false);
    pll_register_string( 'capital_value_assets_label_rfc_form', 'Value of other assets', 'modern-website', false);
    pll_register_string( 'capital_current_balance_label_rfc_form', 'Current balance(s) on loans secured by real estate', 'modern-website', false);
    pll_register_string( 'capital_other_debts_label_rfc_form', 'Other debts', 'modern-website', false);
    pll_register_string( 'stay_informed_label_rfc_form', 'Stay Informed', 'modern-website', false);
    pll_register_string( 'stay_informed_email_label_rfc_form', 'It is OK for us to email you with more information', 'modern-website', false);
    pll_register_string( 'stay_informed_call_label_rfc_form', 'It is OK for us to call regarding this opportunity', 'modern-website', false);
    pll_register_string( 'stay_informed_text_label_rfc_form', 'It is OK for us text you with updates', 'modern-website', false);
    pll_register_string( 'select_all_label_rfc_form', 'Select All', 'modern-website', false);
    pll_register_string( 'disclaimer_label_rfc_form', 'Disclaimer', 'modern-website', false);
    pll_register_string( 'how_did_you_hear_about_us', 'How did you hear about us?', 'modern-website', false);
    pll_register_string( 'text_goes_here', 'Text goes here', 'modern-website', false);
    pll_register_string( 'other_input_label','Other', 'modern-website', false);
    pll_register_string( 'acordion_lang', 'Languages','modern-website', false);
    pll_register_string( 'click_all_that_apply', 'Click all that apply.','modern-website', false);
    pll_register_string( 'spoken_label', 'Spoken', 'modern-website', false);
    pll_register_string( 'written_label', 'Written', 'modern-website', false);
    pll_register_string( 'choose_select', 'Choose...', 'modern-website', false);
    pll_register_string( 'english_proficiency', 'English proficiency', 'modern-website', false);
    pll_register_string( 'geographical_reach', 'Geographical Reach', 'modern-website', false);
    pll_register_string( 'franchise_opportunities', 'Franchise Opportunities', 'modern-website', false);
    pll_register_string( 'franchise_opportunities_id', 'Opportunity ID#', 'modern-website', false);
    pll_register_string( 'submit_application', 'SUBMIT APPLICATION', 'modern-website', false);
    pll_register_string( 'phone_placeholder', 'XXX-XXXX-XXXX', 'modern-website', false);
    pll_register_string( 'please_specify', 'Please specify', 'modern-website', false);
    pll_register_string( 'french_options', 'French', 'modern-website', false);
    pll_register_string( 'english_options', 'English', 'modern-website', false);
    pll_register_string( 'fluent_options', 'Fluent', 'modern-website', false);
    pll_register_string( 'advanced_options', 'Advanced', 'modern-website', false);
    pll_register_string( 'intermediate_options', 'Intermediate', 'modern-website', false);
    pll_register_string( 'elementary_options', 'Elementary', 'modern-website', false);
    pll_register_string( 'beginner_options','Beginner','modern-website', false);
    pll_register_string( 'identify_top_three_markets_label', 'Identify top three markets (City)','modern-website', false);
    pll_register_string( 'option_one', 'Option One','modern-website', false);
    pll_register_string( 'option_two', 'Option Two','modern-website', false);
    pll_register_string( 'option_three', 'Option Three','modern-website', false);
    pll_register_string( 'are_you_willing_label', 'Are you willing to relocate anywhere in Canada? If yes, please provide details.', 'modern-website', true);
    pll_register_string( 'yes_option', 'Yes', 'modern-website', false);
    pll_register_string( 'no_option', 'No', 'modern-website', false);
    pll_register_string( 'business_matters_accordion', 'Business matters / eligibility','modern-website', false);
    pll_register_string( 'are_you_legally_eligible_label','Are you legally eligible to work in Canada?','modern-website', false);
    pll_register_string( 'have_you_ever_owned_your_own_business_or_franchise_label', 'Have you ever owned your own business or Franchise?','modern-website', false);
    pll_register_string( 'name_of_business_or_franchise_placeholder', 'Name of business or Franchise', 'modern-website', false);
    pll_register_string( 'name_of_business_or_franchise_label', 'Specify name of business or Franchise', 'modern-website', false);
    pll_register_string( 'do_you_currently_own_your_own_business_or_franchise_label', 'Do you currently own your own business or Franchise?', 'modern-website', true);
    pll_register_string( 'cleaning_company','Have you ever or do you still work for a cleaning company?', 'modern-website', false);
    pll_register_string( 'specify_name_of_cleaning_company', 'Specify name of cleaning company', 'modern-website', false);
    pll_register_string( 'why_are_you_interested_in_acquiring_a_modern_franchise', 'Why are you interested in acquiring a Modern Franchise?', 'modern-website', true);
    pll_register_string( 'tell_us_why_you_belive','Tell us why you believe you would make an excellent Franchisee for Modern Cleaining?', 'modern-website', true);
    pll_register_string( 'resume_accordion', 'Resume', 'modern-website', false);
    pll_register_string( 'max_file_size_label', 'Max file size 2MB', 'modern-website', false);
    pll_register_string( 'max_file_size_higher_label', 'Max file size 50MB', 'modern-website', false);
    pll_register_string( 'please_read_carefully_label', 'Please Read Carefully', 'modern-website', false);
    pll_register_string( 'provide_details', 'Provide details', 'modern-website', false);

    pll_register_string( 'company_name_label', 'Company Name', 'modern-website', false);
    pll_register_string( 'email_label', 'E-mail', 'modern-website', false);
    pll_register_string( 'phone_number_label', 'Phone Number', 'modern-website', false);
    pll_register_string( 'subject_label', 'Subject', 'modern-website', false);
    pll_register_string( 'subject_placeholder', 'Subject Placeholder', 'modern-website', false);
    pll_register_string( 'how_can_we_help_you', 'How can we help you?', 'modern-website', false);
    pll_register_string( 'how_can_we_help_you_placeholder', 'How can we help you? Placeholder', 'modern-website', false);
    pll_register_string( 'french-and-english', 'French and English', 'modern-website');
     // Contact Us Form Strings
    pll_register_string( 'name_placeholder_contact_us_form', 'Name Contact Us Form', 'modern-website', false);
    pll_register_string( 'email_address_placeholder_contact_us_form', 'Email Address Contact Us Form', 'modern-website', false);
    pll_register_string( 'phone_number_placeholder_contact_us_form', 'Phone Number Contact Us Form', 'modern-website', false);
    pll_register_string( 'phone_number_placeholder_territory_franchise_form', 'Phone Number Territory Franchise Form Placeholder', 'modern-website', false);
    pll_register_string( 'building_address', 'Building Address', 'modern-website', false);
    pll_register_string( 'building_address_placeholder', 'Building Address Placeholder', 'modern-website', false);
    pll_register_string( 'company_name_placeholder', 'Company Name Placeholder', 'modern-website', false);
    pll_register_string( 'select_province', 'Select Province', 'modern-website', false);
    pll_register_string( 'submit', 'Submit', 'modern-website', false);

    // Territory Franchise Form Strings
    pll_register_string( 'first', 'First', 'modern-website', false);
    pll_register_string( 'first_name', 'First Name', 'modern-website', false);
    pll_register_string( 'last', 'Last', 'modern-website', false);
    pll_register_string( 'last_name', 'Last Name', 'modern-website', false);
    pll_register_string( 'first_placeholder', 'First Placeholder', 'modern-website', false);
    pll_register_string( 'last_placeholder', 'Last Placeholder', 'modern-website', false);
    pll_register_string( 'targeted_areas_postal_code', 'Targeted areas (Postal Code)', 'modern-website', false);
    pll_register_string( 'investment_level', 'Investment Level', 'modern-website', false);
    pll_register_string( 'investment_level_placeholder', 'Investment Level Placeholder', 'modern-website', false);

    // Careers/Operations Form Strings
    pll_register_string( 'careers_operations', 'CAREERS/OPERATIONS', 'modern-website', false);
    pll_register_string( 'email_address_career_form_placeholder', 'E-mail Address Career Form Placeholder', 'modern-website', false);
    pll_register_string( 'experience', 'EXPERIENCE', 'modern-website', false);
    pll_register_string( 'company', 'Company', 'modern-website', false);
    pll_register_string( 'company_placeholder', 'Company Placeholder', 'modern-website', false);
    pll_register_string( 'duration', 'Duration', 'modern-website', false);
    pll_register_string( 'duration_placeholder', 'Duration Placeholder', 'modern-website', false);
    pll_register_string( 'add_more', 'Add more', 'modern-website', false);
    pll_register_string( 'attachments', 'ATTACHMENTS', 'modern-website', false);
    pll_register_string( 'upload_file', 'Upload file', 'modern-website', false);
    pll_register_string( 'additional_documents', 'Additional documents (Max file 2MB)', 'modern-website', false);
    pll_register_string( 'disclaimer_careers_form', 'Disclaimer Careers Form', 'modern-website', true);
    pll_register_string( 'submit_your_application', 'Submit your application', 'modern-website', true);
    pll_register_string( 'resume_max_file_size', 'Resume (Max file 2MB)', 'modern-website', false);

    pll_register_string( 'apply_to_this_job', 'Apply To This Job', 'modern-website', true);
    pll_register_string( 'next', 'Next', 'modern-website', true);
    pll_register_string( 'show_all', 'Show all', 'modern-website', true);
    pll_register_string( 'job_id', 'Job ID#', 'modern-website', true);
    pll_register_string( 'job_title', 'Job Title', 'modern-website', true);
    pll_register_string( 'location', 'Location', 'modern-website', true);

    pll_register_string( 'newspaper', 'Newspaper', 'modern-website', true);
    pll_register_string( 'modern-franchisee', 'Modern Franchisee', 'modern-website', true);
    pll_register_string( 'spanish', 'Spanish', 'modern-website', true);

    pll_register_string( 'action', 'Action', 'modern-website', true);
    pll_register_string( 'selection', 'Selection', 'modern-website', true);
    pll_register_string( 'apply_now', 'APPLY NOW', 'modern-website', true);
    pll_register_string( 'franchise_opportunity_instruction', 'Either you want to apply for more than one opportunity or apply as a general applicant, please use the "APPLY BUTTON" below the current franchise opportunities table.', 'modern-website', true);

    
    pll_register_string( 'unit_franchise_disclaimer', 'Unit Franchise Disclaimer', 'modern-website', true);
    pll_register_string( 'territory_franchise_disclaimer', 'Territory Franchise Disclaimer', 'modern-website', true);
    pll_register_string( 'close', 'Close', 'modern-website', true);
    pll_register_string( 'get_started', 'Get started', 'modern-website', true);
    pll_register_string( 'single_industry_form_text', 'Please submit the information below and a member from our team will be in touch to schedule your free cleaning trial.', 'modern-website', true);
    pll_register_string( 'single_industry_form_desclaimer_text', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', 'modern-website', true);

    pll_register_string( 'download_file', 'Download file', 'modern-website', true);
    pll_register_string( 'use_dropdown_for_all_provinces', 'Use dropdown for all provinces', 'modern-website', true);
    pll_register_string( 'use_dropdown_for_all_investment_ranges', 'Use dropdown for all investment ranges', 'modern-website', true);

?>